[package]
name = "gitpr"
version = "0.1.0"
authors = ["Nick Murphy <comfortablynick@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
structopt = "0.2"
termcolor = "1"
chrono = "0.4"
